project_id = "gpomjdrjueixrmqzoyvg"

[functions.scrape-instagram]
verify_jwt = true

[functions.generate-insights]
verify_jwt = true

[functions.receive-instagram-metrics]
verify_jwt = false

[functions.receive-pipedrive-leads]
verify_jwt = false
