project_id = "kzozelpatwzdrmtnsnte"

[functions.receive-pipedrive-leads]
verify_jwt = false

[functions.fetch-reportei-data]
verify_jwt = true

[functions.fetch-pipedrive-data]
verify_jwt = true

[functions.send-metrics-to-n8n]
verify_jwt = true

[functions.analyze-metrics]
verify_jwt = false
